In [111]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup 
from selenium import webdriver
import requests_html
import csv

In [112]:
advanceentrieslist = pd.read_csv('AdvanceEntry.csv')
updateddf = advanceentrieslist[['uscfid', 'FIDE ID']]

In [113]:
URL = 'https://www.vegaschessfestival.com/live/results/'
page = requests.get(URL, headers={'User-Agent': 'Mozilla/5.0'})
soup = BeautifulSoup(page.content, 'lxml')

In [114]:
tables = soup.find_all(class_ = 'doublescroll')
string = tables[0].text
listofrows = string.split('\n')

In [115]:
placement = []
title = []
name = []
federation = []
fide_id = []
fide_rating = []
uscf_rating = []
score = []
round1 = []
round2 = []
round3 = []
round4 = []
round5 = []
round6 = []
round7 = []
round8 = []
round9 = []

In [116]:
for player in listofrows:
    placement.append(player[0:3])
    title.append(player[4:7])
    name.append(player[8:35])
    federation.append(player[35:38])
    fide_id.append(player[39:47])
    fide_rating.append(player[48:53])
    uscf_rating.append(player[54:58])
    score.append(player[59:62])
    round1.append(player[63:67])
    round2.append(player[68:72])
    round3.append(player[73:77])
    round4.append(player[78:82])
    round5.append(player[83:87])
    round6.append(player[88:92])
    round7.append(player[93:97])
    round8.append(player[98:102])
    round9.append(player[103:107])

In [117]:
df = pd.DataFrame(list(zip(placement, title,name,federation,fide_id,fide_rating,uscf_rating,score,round1,round2,round3 ,round4 ,round5 ,round6 ,round7 ,round8,round9 )),
               columns =['Place', 'Title', 'Name', 'Federation', 'Fide ID', 'FIDE rating', 'USCF rating', 'Score', 'Round1', 'Round2', 'Round3', 'Round4', 'Round5', 'Round6', 'Round7', 'Round8', 'Round9'])

In [118]:
df.drop(index=df.index[0], 
        axis=0, 
        inplace=True)

In [119]:
uscflist = updateddf['uscfid'].tolist()
fidelist = updateddf['FIDE ID'].tolist()

In [120]:
newlistuscf = []
for item in uscflist:
    new = item.replace('\xa0', '')
    newlistuscf.append(new)
newlistfide= []

for items in fidelist:
    newz = items.replace('\xa0', '')
    newlistfide.append(newz)

In [121]:
updateddf['real uscf'] = newlistuscf
updateddf['real fide'] = newlistfide

C:\Users\danie\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\danie\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [122]:
updateddf = updateddf.drop(['uscfid', 'FIDE ID'], axis = 1)

In [123]:
joineddf = pd.merge(left=df, right=updateddf, how='left', left_on='Fide ID', right_on='real uscf')

In [124]:
N = 2
joineddf.drop(index=joineddf.index[-N:], 
        axis=0, 
        inplace=True)

In [125]:
df

,Place,Title,Name,Federation,Fide ID,FIDE rating,USCF rating,Score,Round1,Round2,Round3,Round4,Round5,Round6,Round7,Round8,Round9
1,1,GM,"Gareyev,Timur",KS,13262157,2606,2692,3.0,W 45,W 37,W 26,---,---,---,---,---,---
2,2,GM,"Hakobyan,Aram",ARM,16863605,2598,2683,3.0,W 71,W 65,W 27,---,---,---,---,---,---
3,3,IM,"Theodorou,Nikolas",GRE,16770955,2566,2657,3.0,W 47,W 39,W 29,---,---,---,---,---,---
4,4,GM,"Kaidanov,Gregory",KY,12543746,2549,2626,3.0,W 97,W 92,W 32,---,-H-,-H-,---,-H-,---
5,5,GM,"Chandra,Akshat",USA,14864036,2536,2630,3.0,W 73,W 68,W 30,---,---,---,---,---,---
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,133,,"Ross,Josiah Gregory",KS,15765707,,881,0.0,L 93,L 82,L109,---,---,---,---,---,---
134,134,,"Allen,Ronald",CA,30086796,,,0.0,L 19,L 80,L112,---,---,---,---,---,---
135,135,,"Cudney,Riley",CA,30202687,,,0.0,L 42,L 99,L103,---,---,---,---,---,---
136,,,,,,,,,,,,,,,,,
137,,,,,,,,,,,,,,,,,

In [126]:
fideids = joineddf['real fide'].tolist()

In [127]:
len(fideids)

135

In [128]:
fideids

['14200937',
 '13306677',
 '4262875',
 '2008564',
 '25006711',
 '24176460',
 '14129850',
 '2031213',
 '30903114',
 '3503739',
 '13300032',
 '3801497',
 '2093596',
 '2034255',
 '12804444',
 '13603647',
 '30911370',
 '2034239',
 '2096889',
 '14118084',
 '712779',
 '2069342',
 '2008572',
 '4174003',
 '13300512',
 '30909694',
 '2099438',
 '2039311',
 '2024799',
 '2039796',
 '2026384',
 '2090759',
 '2025817',
 '4130413',
 '2062496',
 '2046318',
 '2039877',
 '30909040',
 '2031779',
 '2024292',
 '30939941',
 '2030292',
 '2099659',
 '30914523',
 '30904625',
 '2043688',
 '7003072',
 '5101107',
 '30931649',
 '2018730',
 '30914051',
 '30953499',
 '30953090',
 '30915856',
 '30922216',
 '14116367',
 '2059630',
 '5111080',
 '13301918',
 '2032562',
 '14203626',
 '3520498',
 '2014254',
 '2000563',
 '2078341',
 '2044447',
 '30908124',
 '2000342',
 '30919754',
 '5201632',
 '2000393',
 '30931975',
 '30930880',
 '30908132',
 '30914558',
 '30938228',
 '30919991',
 '30944996',
 '30915708',
 '2079518',
 '2020165',
 '30919860',
 '30921880',
 '30941091',
 '30927838',
 '2097257',
 '30977118',
 '2005492',
 '2087090',
 '2087456',
 '2010011',
 '5114241',
 '30908477',
 '30908485',
 '30908604',
 '30908590',
 '2623897',
 '4168585',
 '13310860',
 '30918804',
 '30952247',
 '2090767',
 '30927420',
 '30919878',
 '2023172',
 '2017288',
 '30941296',
 '30924820',
 '30910544',
 '2037866',
 '30935008',
 '30934885',
 '30976880',
 '30913942',
 '30977967',
 '2012456',
 '30908922',
 '2016516',
 '30952255',
 '30943876',
 '30943868',
 '2016770',
 '2095335',
 '30950961',
 '30977258',
 '',
 nan,
 '30942551',
 '30974801',
 '30955416',
 '8111456',
 '2075369',
 '30925320',
 '30977177',
 '30977886']

In [135]:
therest = fideids[127:136]

In [136]:
listofbirthyears = []
for item in fideids:
    try:
        URL = 'https://ratings.fide.com/profile/' + item
        page = requests.get(URL, headers={'User-Agent': 'Mozilla/5.0'})
        soup = BeautifulSoup(page.content, 'lxml')
        fidecard = soup.findAll('div', class_ = 'profile-top-info__block__row__data')
        year = fidecard[3].text
        listofbirthyears.append(year)
    except:
        listofbirthyears.append('UNKNOWN')

In [ ]:
for item in therest:
    try:
        URL = 'https://ratings.fide.com/profile/' + item
        page = requests.get(URL, headers={'User-Agent': 'Mozilla/5.0'})
        soup = BeautifulSoup(page.content, 'lxml')
        fidecard = soup.findAll('div', class_ = 'profile-top-info__block__row__data')
        year = fidecard[3].text
        listofbirthyears.append(year)
    except:
        listofbirthyears.append('UNKNOWN')

In [141]:
joineddf

,Place,Title,Name,Federation,Fide ID,FIDE rating,USCF rating,Score,Round1,Round2,Round3,Round4,Round5,Round6,Round7,Round8,Round9,real uscf,real fide
0,1,GM,"Gareyev,Timur",KS,13262157,2606,2692,3.0,W 45,W 37,W 26,---,---,---,---,---,---,13262157,14200937
1,2,GM,"Hakobyan,Aram",ARM,16863605,2598,2683,3.0,W 71,W 65,W 27,---,---,---,---,---,---,16863605,13306677
2,3,IM,"Theodorou,Nikolas",GRE,16770955,2566,2657,3.0,W 47,W 39,W 29,---,---,---,---,---,---,16770955,4262875
3,4,GM,"Kaidanov,Gregory",KY,12543746,2549,2626,3.0,W 97,W 92,W 32,---,-H-,-H-,---,-H-,---,12543746,2008564
4,5,GM,"Chandra,Akshat",USA,14864036,2536,2630,3.0,W 73,W 68,W 30,---,---,---,---,---,---,14864036,25006711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,131,,"Mohammad,Saad Al-Deen",JOR,30052876,1463,1538,0.0,L 94,L 50,L110,---,---,-H-,-H-,---,---,30052876,8111456
131,132,,"Lundy,George W",ID,10473357,,1402,0.0,L 43,L101,L111,---,---,---,---,---,---,10473357,2075369
132,133,,"Ross,Josiah Gregory",KS,15765707,,881,0.0,L 93,L 82,L109,---,---,---,---,---,---,15765707,30925320
133,134,,"Allen,Ronald",CA,30086796,,,0.0,L 19,L 80,L112,---,---,---,---,---,---,30086796,30977177
134,135,,"Cudney,Riley",CA,30202687,,,0.0,L 42,L 99,L103,---,---,---,---,---,---,30202687,30977886

In [ ]:
# for item in notnulls:
#     URL = 'https://ratings.fide.com/profile/' + item
#     try:
#         page = requests.get(URL, headers={'User-Agent': 'Mozilla/5.0'})
#         soup = BeautifulSoup(page.content, 'lxml')
#         fidecard = soup.findAll('div', class_ = 'profile-top-info__block__row__data')
#         year = fidecard[3].text
#         listofbirthyears.append(year)
#     except:
#         listofbirthyears.append('UNKNOWN')

In [ ]:
# listofbirthyears[125] = 'UNKNOWN'
# listofbirthyears[126] = 'UNKNOWN'
# listofbirthyears[127] = '1973'
# listofbirthyears[128] = '1998'
# listofbirthyears[129] = '1991'
# listofbirthyears[130] = '1951'
# listofbirthyears[131] = '2003'
# listofbirthyears.append('2000')
# listofbirthyears.append('2001')

In [ ]:
# joineddf['Birth Year'] = listofbirthyears

In [ ]:
# fidecard = soup.findAll('div', class_ = 'profile-top-info__block__row__data')

In [ ]:
# fidecard[3].text

In [ ]:
# len(joineddf)

ValueError: Length of values does not match length of index

In [149]:
len(listofbirthyears)

134

In [158]:
listofbirthyears[126] = 'UNKNOWN'
listofbirthyears[127] = '2001'
listofbirthyears[128] = '1973'
listofbirthyears[129] = '1998'
listofbirthyears[130] = '1991'
listofbirthyears[131] = '1951'
listofbirthyears[132] = '2003'
listofbirthyears[133] = '2000'
listofbirthyears.append('2001')

In [156]:
listofbirthyears[123:]

['2005',
 '1956',
 'UNKNOWN',
 'UNKNOWN',
 '1973',
 '1998',
 '1991',
 '1951',
 '2003',
 '2000',
 '2001']

In [145]:
joineddf[123:]

,Place,Title,Name,Federation,Fide ID,FIDE rating,USCF rating,Score,Round1,Round2,Round3,Round4,Round5,Round6,Round7,Round8,Round9,real uscf,real fide
123,124,,"Finkelstein,Alan",CA,14958842,1760,2048,0.5,L 39,L 98,D117,---,---,---,---,---,---,14958842,30950961
124,125,,"Ross,Joseph Michael",FL,11300791,,1619,0.5,-H-,L 74,L 84,---,---,---,---,---,---,11300791,30977258
125,126,,"Syed,Taimoor",NY,17172077,,1367,0.5,-H-,L 46,L 77,---,---,---,---,---,---,17172077,
126,127,,"Lita,Nick",CA,12701855,,2124,0.0,L 92,L 75,---,---,---,---,---,---,---,NaN,NaN
127,128,,"McConnell,Griffin Thomas",CO,14692997,1823,2041,0.0,L 37,L 97,L 89,---,---,---,---,---,---,14692997,30942551
128,129,,"Garrison,Jay",AZ,12653755,,1723,0.0,L 91,L 78,L104,---,---,---,---,---,---,12653755,30974801
129,130,,"Ner,John Kenneth Tayamora",LA,15446333,1651,1402,0.0,L 38,L 73,L105,---,---,---,---,---,---,15446333,30955416
130,131,,"Mohammad,Saad Al-Deen",JOR,30052876,1463,1538,0.0,L 94,L 50,L110,---,---,-H-,-H-,---,---,30052876,8111456
131,132,,"Lundy,George W",ID,10473357,,1402,0.0,L 43,L101,L111,---,---,---,---,---,---,10473357,2075369
132,133,,"Ross,Josiah Gregory",KS,15765707,,881,0.0,L 93,L 82,L109,---,---,---,---,---,---,15765707,30925320
133,134,,"Allen,Ronald",CA,30086796,,,0.0,L 19,L 80,L112,---,---,---,---,---,---,30086796,30977177
134,135,,"Cudney,Riley",CA,30202687,,,0.0,L 42,L 99,L103,---,---,---,---,---,---,30202687,30977886

In [159]:
joineddf['Birth Year'] = listofbirthyears

In [152]:
len(listofbirthyears)

134

In [153]:
len(joineddf)

135

In [154]:
listofbirthyears

['1988',
 '2001',
 '2000',
 '1959',
 '1999',
 '2000',
 '2002',
 '1996',
 '2006',
 '1982',
 '1971',
 '1991',
 '2003',
 '1993',
 '1998',
 '1993',
 '2005',
 '1996',
 '2000',
 '1996',
 '1999',
 '2001',
 '1967',
 '1993',
 '1970',
 '2006',
 '2004',
 '1996',
 '1982',
 '1996',
 '1992',
 '2005',
 '1987',
 '1984',
 '2003',
 '1994',
 '1995',
 '2004',
 '1988',
 '1978',
 '2007',
 '1996',
 '2003',
 '1994',
 '1999',
 '1994',
 '2010',
 '1981',
 '2007',
 '1962',
 '2004',
 '2010',
 '2000',
 '2008',
 '2009',
 '1998',
 '1999',
 '1995',
 '1988',
 '1993',
 '1999',
 '2002',
 '1981',
 '1959',
 '2002',
 '1998',
 '2006',
 '1960',
 '2004',
 '1987',
 '1953',
 '2006',
 '2006',
 '2006',
 '2002',
 '2006',
 '2005',
 '2005',
 '2006',
 '2000',
 '1983',
 '2007',
 '2003',
 '2007',
 '2006',
 '2003',
 '1997',
 '1958',
 '1998',
 '2000',
 '1981',
 '2000',
 '2006',
 '2003',
 '2006',
 '2006',
 '2008',
 '1985',
 '2004',
 '2005',
 '2006',
 '2005',
 '1995',
 '2007',
 '1982',
 '1974',
 '2009',
 '2004',
 '2005',
 '1983',
 '1998',
 '2006',
 '2000',
 '1970',
 '2001',
 '1981',
 '2006',
 '1983',
 '2007',
 '2007',
 '1999',
 '1943',
 '1952',
 '2005',
 '1956',
 'UNKNOWN',
 'UNKNOWN',
 '1973',
 '1998',
 '1991',
 '1951',
 '2003',
 '2000',
 '2001']

In [160]:
joineddf

,Place,Title,Name,Federation,Fide ID,FIDE rating,USCF rating,Score,Round1,Round2,Round3,Round4,Round5,Round6,Round7,Round8,Round9,real uscf,real fide,Birth Year
0,1,GM,"Gareyev,Timur",KS,13262157,2606,2692,3.0,W 45,W 37,W 26,---,---,---,---,---,---,13262157,14200937,1988
1,2,GM,"Hakobyan,Aram",ARM,16863605,2598,2683,3.0,W 71,W 65,W 27,---,---,---,---,---,---,16863605,13306677,2001
2,3,IM,"Theodorou,Nikolas",GRE,16770955,2566,2657,3.0,W 47,W 39,W 29,---,---,---,---,---,---,16770955,4262875,2000
3,4,GM,"Kaidanov,Gregory",KY,12543746,2549,2626,3.0,W 97,W 92,W 32,---,-H-,-H-,---,-H-,---,12543746,2008564,1959
4,5,GM,"Chandra,Akshat",USA,14864036,2536,2630,3.0,W 73,W 68,W 30,---,---,---,---,---,---,14864036,25006711,1999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,131,,"Mohammad,Saad Al-Deen",JOR,30052876,1463,1538,0.0,L 94,L 50,L110,---,---,-H-,-H-,---,---,30052876,8111456,1991
131,132,,"Lundy,George W",ID,10473357,,1402,0.0,L 43,L101,L111,---,---,---,---,---,---,10473357,2075369,1951
132,133,,"Ross,Josiah Gregory",KS,15765707,,881,0.0,L 93,L 82,L109,---,---,---,---,---,---,15765707,30925320,2003
133,134,,"Allen,Ronald",CA,30086796,,,0.0,L 19,L 80,L112,---,---,---,---,---,---,30086796,30977177,2000
134,135,,"Cudney,Riley",CA,30202687,,,0.0,L 42,L 99,L103,---,---,---,---,---,---,30202687,30977886,2001

In [161]:
joineddf.to_csv('birthyears.csv')